### ISSUE TITLE
Initial SQL table

### ISSUE THREAD

**Issue by ad-m** [joepie91/pdfy#24]
Hi!

Thanks for very interesting software. I also think about something this kind. 

I would like install own instantion, but...I can't find initial sql schema. Where I can found it? In file /upgrades/1.sql I can find only ALTER TABLE, but  nowhere CREATE TABLE.

By code analysis I can support there is only 1 table - documents (SlugId,Filename, IsPublic, OriginalFilename, DeleteKey, UploadDate, Views), but I think this is good habit to include sql in repo.

Greatings,
Adam Dobrawy

**Comment by ad-m** [comment]
``` sql
CREATE TABLE IF NOT EXISTS `documents` (
  `SlugId` char(16) NOT NULL,
  `Filename` varchar(80) NOT NULL,
  `OriginalFilename` varchar(80) NOT NULL,
  `Views` int(11) NOT NULL,
  `Public` int(1) NOT NULL,
  `DeleteKey` char(32) NOT NULL,
  `Uploaded` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id`),
  KEY `SlugId` (`SlugId`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2;

INSERT INTO `documents` (`SlugId`, `Filename`, `OriginalFilename`, `Views`, `Public`, `DeleteKey`, `Uploaded`, `Id`) VALUES
('GK0cVH4icY5oSRCd', '5yVxl4qjjfoO7CWJ', '7-bytow-anon.pdf', 2, 1, 'AXx6obaJ3yxsGYuHQTL7CiS0ZvQYyNT4', 2014, 2);
```

I creating something like that. Initial row are necesarry. So, now I am looking for support Amazon S3 & Tiktalik.

**Comment by joepie91** [comment]
Whoops, sorry for that! I've added it now: https://github.com/joepie91/pdfy/blob/master/schema.sql

**Comment by ad-m** [comment]
Initial record are required too...
![zaznaczenie_166](https://cloud.githubusercontent.com/assets/3618479/3638718/b1c75c1a-105b-11e4-9da0-5d1c4162e279.png)

**Comment by joepie91** [comment]
That was a bug in the gallery display code, actually; it should be fixed with the latest commit.
